export const countries = [
  { name: "Afghanistan", url: "AF" },
  { name: "Åland Islands", url: "AX" },
  { name: "Albania", url: "AL" },
  { name: "Algeria", url: "DZ" },
  { name: "Andorra", url: "AD" },
  { name: "Angola", url: "AO" },
  { name: "Argentina", url: "AR" },
  { name: "Armenia", url: "AM" },
  { name: "Aruba", url: "AW" },
  { name: "Australia", url: "AU" },
  { name: "Austria", url: "AT" },
  { name: "Azerbaijan", url: "AZ" },
  { name: "Bahrain", url: "BH" },
  { name: "Bangladesh", url: "BD" },
  { name: "Barbados", url: "BB" },
  { name: "Belarus", url: "BY" },
  { name: "Belgium", url: "BE" },
  { name: "Belize", url: "BZ" },
  { name: "Bolivia", url: "BO" },
  { name: "Bosnia and Herzegovina", url: "BA" },
  { name: "Botswana", url: "BW" },
  { name: "Brazil", url: "BR" },
  { name: "Brunei", url: "BN" },
  { name: "Bulgaria", url: "BG" },
  { name: "Cambodia", url: "KH" },
  { name: "Canada", url: "CA" },
  { name: "Chile", url: "CL" },
  { name: "China", url: "CN" },
  { name: "Colombia", url: "CO" },
  { name: "Costa Rica", url: "CR" },
  { name: "Croatia", url: "HR" },
  { name: "Cuba", url: "CU" },
  { name: "Curaçao", url: "CW" },
  { name: "Cyprus", url: "CY" },
  { name: "Czechia", url: "CZ" },
  { name: "Denmark", url: "DK" },
  { name: "Dominican Republic", url: "DO" },
  { name: "East Timor", url: "TL" },
  { name: "Ecuador", url: "EC" },
  { name: "Egypt", url: "EG" },
  { name: "El Salvador", url: "SV" },
  { name: "Estonia", url: "EE" },
  { name: "Ethiopia", url: "ET" },
  { name: "Falkland Islands", url: "FK" },
  { name: "Faroe Islands", url: "FO" },
  { name: "Finland", url: "FI" },
  { name: "France", url: "FR" },
  { name: "French Guiana", url: "GF" },
  { name: "French Polynesia", url: "PF" },
  { name: "Georgia", url: "GE" },
  { name: "Germany", url: "DE" },
  { name: "Gibraltar", url: "GI" },
  { name: "Greece", url: "GR" },
  { name: "Greenland", url: "GL" },
  { name: "Guadeloupe", url: "GP" },
  { name: "Guam", url: "GU" },
  { name: "Guatemala", url: "GT" },
  { name: "Guernsey", url: "GG" },
  { name: "Guyana", url: "GY" },
  { name: "Honduras", url: "HN" },
  { name: "Hong Kong", url: "HK" },
  { name: "Hungary", url: "HU" },
  { name: "Iceland", url: "IS" },
  { name: "India", url: "IN" },
  { name: "Indonesia", url: "ID" },
  { name: "International", url: "XX" },
  { name: "Iran", url: "IR" },
  { name: "Iraq", url: "IQ" },
  { name: "Ireland", url: "IE" },
  { name: "Isle of Man", url: "IM" },
  { name: "Israel", url: "IL" },
  { name: "Italy", url: "IT" },
  { name: "Jamaica", url: "JM" },
  { name: "Japan", url: "JP" },
  { name: "Jersey", url: "JE" },
  { name: "Jordan", url: "JO" },
  { name: "Kazakhstan", url: "KZ" },
  { name: "Kenya", url: "KE" },
  { name: "Korea, South", url: "KR" },
  { name: "Kuwait", url: "KW" },
  { name: "Kyrgyzstan", url: "KG" },
  { name: "Laos", url: "LA" },
  { name: "Latvia", url: "LV" },
  { name: "Lebanon", url: "LB" },
  { name: "Libya", url: "LY" },
  { name: "Liechtenstein", url: "LI" },
  { name: "Lithuania", url: "LT" },
  { name: "Luxembourg", url: "LU" },
  { name: "Madagascar", url: "MG" },
  { name: "Malawi", url: "MW" },
  { name: "Malaysia", url: "MY" },
  { name: "Maldives", url: "MV" },
  { name: "Malta", url: "MT" },
  { name: "Mauritius", url: "MU" },
  { name: "Mexico", url: "MX" },
  { name: "Moldova", url: "MD" },
  { name: "Monaco", url: "MC" },
  { name: "Mongolia", url: "MN" },
  { name: "Montenegro", url: "ME" },
  { name: "Morocco", url: "MA" },
  { name: "Mozambique", url: "MZ" },
  { name: "Myanmar", url: "MM" },
  { name: "Namibia", url: "NA" },
  { name: "Nepal", url: "NP" },
  { name: "Netherlands", url: "NL" },
  { name: "New Caledonia", url: "NC" },
  { name: "New Zealand", url: "NZ" },
  { name: "Nicaragua", url: "NI" },
  { name: "North Macedonia", url: "MK" },
  { name: "Norway", url: "NO" },
  { name: "Oman", url: "OM" },
  { name: "Pakistan", url: "PK" },
  { name: "Palestine", url: "PS" },
  { name: "Panama", url: "PA" },
  { name: "Paraguay", url: "PY" },
  { name: "Peru", url: "PE" },
  { name: "Philippines", url: "PH" },
  { name: "Poland", url: "PL" },
  { name: "Portugal", url: "PT" },
  { name: "Puerto Rico", url: "PR" },
  { name: "Qatar", url: "QA" },
  { name: "Reunion", url: "RE" },
  { name: "Romania", url: "RO" },
  { name: "Russia", url: "RU" },
  { name: "Saint Pierre and Miquelon", url: "PM" },
  { name: "San Marino", url: "SM" },
  { name: "Saudi Arabia", url: "SA" },
  { name: "Serbia", url: "RS" },
  { name: "Singapore", url: "SG" },
  { name: "Slovakia", url: "SK" },
  { name: "Slovenia", url: "SI" },
  { name: "Somalia", url: "SO" },
  { name: "South Africa", url: "ZA" },
  { name: "Spain", url: "ES" },
  { name: "Sri Lanka", url: "LK" },
  { name: "Suriname", url: "SR" },
  { name: "Svalbard", url: "SJ" },
  { name: "Sweden", url: "SE" },
  { name: "Switzerland", url: "CH" },
  { name: "Syria", url: "SY" },
  { name: "Taiwan", url: "TW" },
  { name: "Tajikistan", url: "TJ" },
  { name: "Thailand", url: "TH" },
  { name: "Trinidad and Tobago", url: "TT" },
  { name: "Tunisia", url: "TN" },
  { name: "Türkiye", url: "TR" },
  { name: "Turkmenistan", url: "TM" },
  { name: "Uganda", url: "UG" },
  { name: "Ukraine", url: "UA" },
  { name: "United Arab Emirates", url: "AE" },
  { name: "United Kingdom", url: "GB" },
  { name: "United States", url: "US" },
  { name: "Unknown", url: "ZZ" },
  { name: "Uruguay", url: "UY" },
  { name: "Uzbekistan", url: "UZ" },
  { name: "Venezuela", url: "VE" },
  { name: "Vietnam", url: "VN" },
  { name: "Zimbabwe", url: "ZW" },
];
